from features import Model,Size,Brand,Cost,Picture,Sound

#taking the sample data
dictionary = []
#sony 55,49
dictionary.append(Model(0,'KD-55A1',Size.FiftyFive, Brand.Sony, Cost.Premium, Picture.UHD, Sound.W50))
dictionary.append(Model(1,'KD-55X9500E',Size.FiftyFive, Brand.Sony, Cost.Premium, Picture.UHD, Sound.W60))
dictionary.append(Model(2,'KD-55X9300E',Size.FiftyFive, Brand.Sony, Cost.VeryHigh, Picture.UHD, Sound.W50))
dictionary.append(Model(3,'KD-55X9000E',Size.FiftyFive, Brand.Sony, Cost.VeryHigh, Picture.UHDTRI, Sound.W20))
dictionary.append(Model(4,'KD-55X8200E',Size.FiftyFive, Brand.Sony, Cost.VeryHigh, Picture.UHDTRI, Sound.W40))
dictionary.append(Model(5,'KD-55X7002E',Size.FiftyFive, Brand.Sony, Cost.High, Picture.UHD, Sound.W20))
dictionary.append(Model(6,'KD-49X9000E',Size.FortyNine, Brand.Sony, Cost.High, Picture.UHDTRI, Sound.W20))
dictionary.append(Model(7,'KD-49X8200E',Size.FortyNine, Brand.Sony, Cost.High, Picture.UHDTRI, Sound.W40))
dictionary.append(Model(8,'KD-49X7500E',Size.FortyNine, Brand.Sony, Cost.High, Picture.UHD, Sound.W20))
dictionary.append(Model(9,'KD-49X7002E',Size.FortyNine, Brand.Sony, Cost.Medium, Picture.UHD, Sound.W20))
dictionary.append(Model(10,'KD-49W772E',Size.FortyNine, Brand.Sony, Cost.Medium, Picture.FHDTRI, Sound.W30))
dictionary.append(Model(11,'KD-49W672E',Size.FortyNine, Brand.Sony, Cost.Low, Picture.FHD, Sound.W30))
#samsung 55,49
dictionary.append(Model(12,'55Q8C',Size.FiftyFive, Brand.Samsung, Cost.Premium, Picture.UHD, Sound.W60))
dictionary.append(Model(13,'55Q7F',Size.FiftyFive, Brand.Samsung, Cost.Premium, Picture.UHD, Sound.W60))
dictionary.append(Model(14,'LS003',Size.FiftyFive, Brand.Samsung, Cost.Premium, Picture.UHD, Sound.W60))
dictionary.append(Model(15,'55MU7000',Size.FiftyFive, Brand.Samsung, Cost.VeryHigh, Picture.UHD, Sound.W40))
dictionary.append(Model(16,'55MU6470',Size.FiftyFive, Brand.Samsung, Cost.High, Picture.UHD, Sound.W20))
dictionary.append(Model(17,'55MU7500',Size.FiftyFive, Brand.Samsung, Cost.VeryHigh, Picture.UHD, Sound.W40))
dictionary.append(Model(18,'55M6300',Size.FiftyFive, Brand.Samsung, Cost.High, Picture.FHD, Sound.W20))
dictionary.append(Model(19,'55M5570',Size.FiftyFive, Brand.Samsung, Cost.High, Picture.FHD, Sound.W20))
dictionary.append(Model(20,'49MU7000',Size.FortyNine, Brand.Samsung, Cost.VeryHigh, Picture.UHD, Sound.W20))
dictionary.append(Model(21,'49MU6470',Size.FortyNine, Brand.Samsung, Cost.High, Picture.UHD, Sound.W20)) 
dictionary.append(Model(22,'49M6300',Size.FortyNine, Brand.Samsung, Cost.Medium, Picture.FHD, Sound.W20))
dictionary.append(Model(23,'49M5570',Size.FortyNine, Brand.Samsung, Cost.Medium, Picture.FHD, Sound.W20))
dictionary.append(Model(24,'49K5300',Size.FortyNine, Brand.Samsung, Cost.Medium, Picture.FHD, Sound.W20))
dictionary.append(Model(25,'49M5100',Size.FortyNine, Brand.Samsung, Cost.Low, Picture.FHD, Sound.W20))
#lg 55,49
dictionary.append(Model(26,'OLEDE7',Size.FiftyFive, Brand.LG, Cost.Premium, Picture.UHD, Sound.W40))
dictionary.append(Model(27,'OLEDC7',Size.FiftyFive, Brand.LG, Cost.Premium, Picture.UHD, Sound.W40))
dictionary.append(Model(28,'OLEDB7',Size.FiftyFive, Brand.LG, Cost.VeryHigh, Picture.UHD, Sound.W40))
dictionary.append(Model(29,'SJ85',Size.FiftyFive, Brand.LG, Cost.VeryHigh, Picture.UHD, Sound.W40))
dictionary.append(Model(30,'SJ80',Size.FiftyFive, Brand.LG, Cost.VeryHigh, Picture.UHD, Sound.W20))
dictionary.append(Model(31,'UJ75',Size.FiftyFive, Brand.LG, Cost.VeryHigh, Picture.UHD, Sound.W20))
dictionary.append(Model(32,'UJ65',Size.FiftyFive, Brand.LG, Cost.High, Picture.UHD, Sound.W20))
dictionary.append(Model(33,'UJ632T',Size.FiftyFive, Brand.LG, Cost.High, Picture.UHD, Sound.W20))
dictionary.append(Model(34,'LJ550T',Size.FiftyFive, Brand.LG, Cost.High, Picture.FHD, Sound.W20))
dictionary.append(Model(35,'SJ800T',Size.FortyNine, Brand.LG, Cost.VeryHigh, Picture.UHD, Sound.W20))
dictionary.append(Model(36,'UJ752T',Size.FortyNine, Brand.LG, Cost.High, Picture.UHD, Sound.W20))
dictionary.append(Model(37,'UJ652T',Size.FortyNine, Brand.LG, Cost.Medium, Picture.UHD, Sound.W20))
dictionary.append(Model(38,'UJ632T',Size.FortyNine, Brand.LG, Cost.Medium, Picture.UHD, Sound.W20))
dictionary.append(Model(39,'L561',Size.FortyNine, Brand.LG, Cost.Medium, Picture.FHD, Sound.W20))
dictionary.append(Model(40,'L5617T',Size.FortyNine, Brand.LG, Cost.Medium, Picture.FHD, Sound.W20))
dictionary.append(Model(41,'LJ554T',Size.FortyNine, Brand.LG, Cost.Low, Picture.FHD, Sound.W20))
dictionary.append(Model(42,'UH5765',Size.FortyNine, Brand.LG, Cost.Medium, Picture.FHD, Sound.W20))
#sony 43
dictionary.append(Model(43,'KD-43X8200E',Size.FortyThree, Brand.Sony, Cost.Medium, Picture.UHD, Sound.W40))
dictionary.append(Model(44,'KD-43X7500E',Size.FortyThree, Brand.Sony, Cost.Medium, Picture.UHD, Sound.W20))
dictionary.append(Model(45,'KD-43X7002E',Size.FortyThree, Brand.Sony, Cost.Medium, Picture.UHD, Sound.W20))
dictionary.append(Model(46,'KD-43W772E',Size.FortyThree, Brand.Sony, Cost.Low, Picture.FHDTRI, Sound.W30))
#samsung 43
dictionary.append(Model(47,'43KU6470',Size.FortyThree, Brand.Samsung, Cost.Medium, Picture.UHD, Sound.W20))
dictionary.append(Model(48,'43MU6100',Size.FortyThree, Brand.Samsung, Cost.Medium, Picture.UHD, Sound.W20))
dictionary.append(Model(49,'43M5570',Size.FortyThree, Brand.Samsung, Cost.Low, Picture.FHD, Sound.W20))
dictionary.append(Model(50,'43K5300',Size.FortyThree, Brand.Samsung, Cost.Low, Picture.FHD, Sound.W20))
dictionary.append(Model(51,'43M5100',Size.FortyThree, Brand.Samsung, Cost.Low, Picture.FHD, Sound.W20))
dictionary.append(Model(52,'43K5002',Size.FortyThree, Brand.Samsung, Cost.Low, Picture.FHD, Sound.W14))
#lg 43
dictionary.append(Model(53,'43UJ752T',Size.FortyThree, Brand.LG, Cost.Medium, Picture.UHD, Sound.W20))
dictionary.append(Model(54,'43UJ652T',Size.FortyThree, Brand.LG, Cost.Medium, Picture.UHD, Sound.W20))
dictionary.append(Model(55,'43UJ632T',Size.FortyThree, Brand.LG, Cost.Medium, Picture.UHD, Sound.W20))
dictionary.append(Model(56,'43LJ619T',Size.FortyThree, Brand.LG, Cost.Low, Picture.FHD, Sound.W40))
dictionary.append(Model(57,'43LJ617T',Size.FortyThree, Brand.LG, Cost.Low, Picture.FHD, Sound.W20))
dictionary.append(Model(58,'43LJ5540T',Size.FortyThree, Brand.LG, Cost.Low, Picture.FHD, Sound.W20))
dictionary.append(Model(59,'43LH576T',Size.FortyThree, Brand.LG, Cost.Low, Picture.FHD, Sound.W20))
dictionary.append(Model(60,'43LJ548T',Size.FortyThree, Brand.LG, Cost.Low, Picture.FHD, Sound.W40))
dictionary.append(Model(61,'43LJ531T',Size.FortyThree, Brand.LG, Cost.Low, Picture.FHD, Sound.W20))
dictionary.append(Model(62,'43LJ525T',Size.FortyThree, Brand.LG, Cost.Low, Picture.FHD, Sound.W20))
dictionary.append(Model(63,'43LJ523T',Size.FortyThree, Brand.LG, Cost.Low, Picture.FHD, Sound.W20))
dictionary.append(Model(64,'43LJ522T',Size.FortyThree, Brand.LG, Cost.Low, Picture.FHD, Sound.W20))

